encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"

urlpatterns = [
    path("", views.index, name="index"),
    path("search/", views.search, name="search"),
    path("newpage/", views.newpage, name="newpage"),
    path("randompage/", views.randompage, name="randompage"),
    path("edit/<str:subject>", views.editpage, name="editpage"),
    path("<str:title>", views.content, name="content"),
]

mail/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),

    # API Routes
    path("emails", views.compose, name="compose"),
    path("emails/<int:email_id>", views.email, name="email"),
    path("emails/<str:mailbox>", views.mailbox, name="mailbox"),
]

project3/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mail.urls'))
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wiki/', include("encyclopedia.urls")),
    # path('', include("encyclopedia.urls")),
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
from django import forms
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib import messages

from markdown2 import Markdown
from . import util
import os
import random

BASE_PATH = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

class NewTaskForm(forms.Form):
    sub_input = forms.CharField(label="", widget=forms.TextInput(attrs={"placeholder":"Type in the subject title here."}))
    content_input = forms.CharField(label="", widget=forms.Textarea(attrs={"placeholder":"Type in the subject title here."}))

    def __init__(self, *args, **kwargs):

        super(NewTaskForm, self).__init__(*args, **kwargs)
        self.fields['sub_input'].initial = ""
        self.fields['content_input'].initial = ""


def index(request):

    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })


def content(request, title):

    pages_list = util.list_entries()
    return_list = [page for page in pages_list if title.lower() == page.lower()]

    if len(return_list) == 0:

        title = "Oops! ERROR 404: requested page was not found."

        return render(request, "encyclopedia/page_error.html", {
                "title": "Oops! ERROR 404: requested page was not found.",
                })

    markdown = md2html(return_list[0])

    return render(request, "encyclopedia/page_content.html", {
        "title": title,
        "markdown": markdown
    })

    # return HttpResponseRedirect(reverse("encyclopedia:title", kwargs={'title': title}))


def search(request):

    if request.method == "POST":

        submit_value = request.POST.get('q')
        return_list = str_matching(submit_value)

        if len(return_list) == 1 and submit_value.lower() == return_list[0].lower():

            return HttpResponseRedirect('/wiki/'+return_list[0])

        else:

            return render(request, "encyclopedia/search_result.html", {
                "query": submit_value,
                "searchResults": return_list,
                "resultNum": len(return_list)
            })


def newpage(request):

    if request.method == "POST":

        # Take in the data the user submitted and save it as form
        form = NewTaskForm(request.POST)

        # Check if form data is valid (server-side)
        if form.is_valid():

            # Isolate the task from the 'cleaned' version of form data, get the data from submit form.
            sub = form.cleaned_data["sub_input"]
            paragraph = form.cleaned_data["content_input"]

            if sub.capitalize() not in util.list_entries():

                # Write the data into a new file.md
                f = open(os.path.join(BASE_PATH, 'entries', sub[:1].capitalize() + sub[1:] +'.md'), 'w+')
                f.write(paragraph)
                f.close()

                return HttpResponseRedirect(reverse("encyclopedia:index"))
            
            else:
                messages.error(request, "This thread has been created.")
                messages.error(request, "Please make a change.")

                return render(request, "encyclopedia/page_new.html", {
                    "form": form
                })
        else:
            return render(request, "encyclopedia/page_new.html", {
                "form": form
            })      

    return render(request, "encyclopedia/page_new.html", {
        "form": NewTaskForm()
    })

def editpage(request, subject):

    if request.method == "GET":
        
        form = NewTaskForm()

        f = open(os.path.join(BASE_PATH, 'entries', subject+'.md'), 'r')

        form.fields['sub_input'].initial = subject
        form.fields['content_input'].initial = f.read()

        return render(request, "encyclopedia/page_edit.html", {
            "form": form
        })

    else:
        
        form = NewTaskForm(request.POST)

        if form.is_valid():
            
            sub = form.cleaned_data["sub_input"]
            paragraph = form.cleaned_data["content_input"]

            # Write the data into a new file.md
            f = open(os.path.join(BASE_PATH, 'entries', sub +'.md'), 'w+')
            f.write(paragraph)
            f.close()

            return HttpResponseRedirect('/wiki/'+sub)


def randompage(request):

    pages_list = util.list_entries()
    ramdom_num = random.randint(0, len(pages_list) - 1)
    page_random = pages_list[ramdom_num]
   

    return HttpResponseRedirect('/wiki/'+page_random) # Redirect after POST


def str_matching(str1):

    pages_list = util.list_entries()
    return_list = [page for page in pages_list if str1.lower() in page.lower()]

    return return_list


def md2html(fname):

    markdowner = Markdown()

    f = open(os.path.join(BASE_PATH, 'entries', fname+'.md'), 'r')

    return markdowner.convert(f.read())

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:content' title=entry %}">{{ entry }}</li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="post">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:newpage' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:randompage' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

<style>
    {% block style %}
    {% endblock %}
</style>

encyclopedia/templates/encyclopedia/page_content.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}

    {% autoescape off %}
        {{ markdown }}
    {% endautoescape %}
    <br><br>
    <a href="edit/{{title}}">[ Edit ]</a>
{% endblock %}

encyclopedia/templates/encyclopedia/page_edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit Page
{% endblock %}

{% block body %}
    <h1>Edit Page</h1>
    <hr>
    {% comment %} <form action="{% url 'encyclopedia:editpage' None %}" method="post"> {% endcomment %}
    <form action="/wiki/edit/{{ form.sub_input.initial }}" method="post">
        {% csrf_token %}
        {{ form.sub_input }}
        <br><br>
        {{ form.content_input }}
        <br>
        <button type="submit">Save Changes</button>
    </form>
{% endblock %}

{% block style %}
    form input {
        width:230px;
    }
    form textarea {
        width:80%;height:50vh;resize: none;
    }
{% endblock %}

encyclopedia/templates/encyclopedia/page_error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    <h1>{{ title }}</h1>
{% endblock %}

encyclopedia/templates/encyclopedia/page_new.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create New Page
{% endblock %}

{% block body %}
    <h1>Create New Page</h1>
    <hr>
    <form action="{% url 'encyclopedia:newpage' %}" method="post">
        {% csrf_token %}
        {{ form.sub_input }}
        <br><br>
        {{ form.content_input }}
        <br>
        <button type="submit">Submit</button>
    </form>
    <br>
    {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endblock %}

{% block style %}
    form input {
        width:230px;
    }
    form textarea {
        width:80%;height:50vh;resize: none;
    }
{% endblock %}

encyclopedia/templates/encyclopedia/search_result.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search Result
{% endblock %}


{% block body %}
    <h1> Search Result</h1>
    <hr>
    <p>"{{ query }}"</p>
    <p>[ {{ resultNum }} total results found. ]</p>
    {% for searchResult in searchResults %}
        <li><a href="{% url 'encyclopedia:content' title=searchResult %}">{{ searchResult }}</a></li>
    {% endfor %}
{% endblock %}